[window]
dimensions = { columns = 80, lines = 30 }
opacity = 0.9

[font]
size = 9.0
normal = { family = "Iosevka Term Extended", style = "Regular" }
bold = { family = "Iosevka Term Extended", style = "Bold" }
bold_italic = { family = "Iosevka Term Extended", style = "Bold Italic" }
italic = { family = "Iosevka Term Extended", style = "Italic" }

[colors.primary]
background = "#3f3f3f"
foreground = "#dcdccc"

[colors.normal]
black = "#3f3f3f"
red = "#cc9393"
green = "#7f9f7f"
yellow = "#d0bf8f"
blue = "#6ca0a3"
magenta = "#dc8cc3"
cyan = "#93e0e3"
white = "#dcdccc"

[colors.bright]
black = "#000000"
red = "#dca3a3"
green = "#bfebbf"
yellow = "#f0dfaf"
blue = "#8cd0d3"
magenta = "#dc8cc3"
cyan = "#93e0e3"
white = "#ffffff"

[colors.cursor]
cursor = "#aaaaaa"
text = "#366060"
